### ISSUE TITLE
Why completely rewrite the extension from scratch? (+feedback)

### ISSUE THREAD

**Issue by tjbulick** [athyuttamre/locale-switcher#30]
Hey! I'm just curious why you decided to do that. Were there any problems or lack of functionality in the previous version before 1.0.0?

As a developer who uses this extension on every day basis, honestly i was just shocked when i saw previously unseen icon in my chrome extensions bar. It reminds me of google translate, not of locale switcher. Early used globe icon was more clearer.

And the design, in my opinion, became heavier and a bit old-fashioned (due to the yellow-ish background color)

And even performance slowed down in contrast to good old version, because of being written in modern framework (or because of api calls?). Can be seen with the naked eye, it takes longer to render and opens with small lag. Sadly.

I'm not to say that all updates are bad and redesigns too, but maybe we need to work more on core functions of this extension such as **speed, very basic design and unambiguity**. The icon should be definitely changed to more suitable one.

<details>
<summary>P.S.</summary>

First thing that came to my mind when i saw this:
![image](https://user-images.githubusercontent.com/28315191/149020449-5cdbcfa9-193b-4cb1-ab20-9e0af6e055c6.png)
was "Why the hell did a new translator extension get installed without me asking?"
</details>

**Comment by cupcakearmy** [comment]
Hey there, thanks for the feedback!
So rewrite was my doing/fault.

Performance:
TBH I don't know the answer, did not seem different to me. Was react before and svelte now. svelte does not have a runtime so can't be that. API calls were made async because of a race condition in the content script. So that might be the reason? again, not sure about that. I can look into startup times.

Design:
Personally I thought the design looked a bit dated so made a new one. It definetely has more character, so not might be for everyone, but as always some will like it, some not. The background coudl be made more white, i agree :)
About the icon.. definetely inspired by translation icons. Might not been the best idea but reverting might cause even more confusion at this point.

About core functions: we made a lot of improvements that were asked by users:
- locale are not global but scoped to tab
- you can star your most used languages 
- more languages
- complete shortcut enabled, you can do everything without touching the mouse (with should be faster to use)
- support fur multiple locale (almost done, will release the next days)

**Comment by maxh-** [comment]
Appreciate most of these changes, but can we configure the setting to be global again? Having to enable it for every tab is not feasible for my workflow 😕

**Comment by cupcakearmy** [comment]
#29 It's in the making

**Comment by tjbulick** [comment]
Appreciate the features you implemented. Especially keyboard accessibility.

> About the icon.. definetely inspired by translation icons. Might not been the best idea but reverting might cause even more confusion at this point.

Why reverting might cause confusion? Maybe the other way around? I guess the old icon is recognized by most of people.
